/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yumxpress.gui;

import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import yumxpress.dao.CustomerDAO;
import yumxpress.pojo.CustomerPojo;
import yumxpress.utility.UserProfile;
import yumxpress.utility.PasswordEncryption;

/**
 *
 * @author its._royal_ankit
 */
public class CustomerLoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustomerLoginFrame
     */
    private JFrame showFrame;
    public CustomerLoginFrame() {
        initComponents();
        setLocationRelativeTo(null);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel2 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        myPanelCustomerLogin = new javax.swing.JPanel();
        lblCustomerLogin = new javax.swing.JLabel();
        lblCustomerLoginImage = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblEmailId = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblNewCustomerRegister = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        myPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(0, 153, 255));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        myPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 432, 173, 46));

        myPanelCustomerLogin.setBackground(new java.awt.Color(0, 153, 255));

        lblCustomerLogin.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        lblCustomerLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomerLogin.setText("Customer Login");

        lblCustomerLoginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/icons/login.png"))); // NOI18N

        javax.swing.GroupLayout myPanelCustomerLoginLayout = new javax.swing.GroupLayout(myPanelCustomerLogin);
        myPanelCustomerLogin.setLayout(myPanelCustomerLoginLayout);
        myPanelCustomerLoginLayout.setHorizontalGroup(
            myPanelCustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelCustomerLoginLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(myPanelCustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelCustomerLoginLayout.createSequentialGroup()
                        .addComponent(lblCustomerLoginImage, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelCustomerLoginLayout.createSequentialGroup()
                        .addComponent(lblCustomerLogin)
                        .addGap(28, 28, 28))))
        );
        myPanelCustomerLoginLayout.setVerticalGroup(
            myPanelCustomerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelCustomerLoginLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lblCustomerLogin)
                .addGap(18, 18, 18)
                .addComponent(lblCustomerLoginImage, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        myPanel2.add(myPanelCustomerLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        myPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 432, 172, 46));

        lblEmailId.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblEmailId.setForeground(new java.awt.Color(0, 153, 255));
        lblEmailId.setText("Enter Email");
        myPanel2.add(lblEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 60, -1, -1));

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 153, 255));
        lblPassword.setText("Enter Password");
        myPanel2.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 191, -1, -1));

        txtEmailId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmailId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 1, true));
        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });
        myPanel2.add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 107, 425, 40));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 249, 425, 40));

        lblNewCustomerRegister.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNewCustomerRegister.setForeground(new java.awt.Color(0, 153, 255));
        lblNewCustomerRegister.setText("New Customer Register Here");
        lblNewCustomerRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewCustomerRegisterMouseClicked(evt);
            }
        });
        myPanel2.add(lblNewCustomerRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 302, 425, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator1.setAlignmentX(5.0F);
        jSeparator1.setAlignmentY(5.0F);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));
        myPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 331, 345, 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(myPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(myPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
         if(!validateInputs()){
         JOptionPane.showMessageDialog(null,"Company Name/Password cannot be left blank");
         return;
     }
     try{
         String emailId=txtEmailId.getText().trim();
         String password=String.valueOf(txtPassword.getPassword()).trim();
         password=PasswordEncryption.getEncryptedPassword(password);
         CustomerPojo cust=CustomerDAO.validate(emailId, password);
         if(cust==null){
             JOptionPane.showMessageDialog(null,"Invalid UserId/Password. Try Again");
             clearAll();
             return;
         }
         UserProfile.setEmailId(cust.getEmailId());
         UserProfile.setUserName(cust.getCustomerName());
         UserProfile.setUserId(cust.getCustomerId());
         CustomerOptionFrame optionsFrame=new CustomerOptionFrame();
         optionsFrame.setVisible(true);
         this.dispose();        
         
     }catch(SQLException ex){
         JOptionPane.showMessageDialog(null,"DB Error In SellerLoginFrame");
         ex.printStackTrace();
         return;
     }
    }                                        
    private boolean validateInputs(){
        
        if(txtEmailId.getText().trim().isEmpty()||String.valueOf(txtPassword.getPassword()).trim().isEmpty()){
            return false;
        }
        return true;
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        UserVerifyFrame userVerify=new UserVerifyFrame();
        userVerify.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void lblNewCustomerRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewCustomerRegisterMouseClicked
        CustomerRegistrationFrame custFrame=new CustomerRegistrationFrame();
        custFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblNewCustomerRegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerLoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCustomerLogin;
    private javax.swing.JLabel lblCustomerLoginImage;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblNewCustomerRegister;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPanel myPanel2;
    private javax.swing.JPanel myPanelCustomerLogin;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
        
    
    private void clearAll() {
        this.txtEmailId.setText("");
        this.txtPassword.setText("");
        this.txtEmailId.requestFocus();
        
    }


}
