/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yumxpress.gui;

import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import yumxpress.dao.StaffDAO;
import yumxpress.pojo.StaffPojo;
import yumxpress.utility.PasswordEncryption;
import yumxpress.utility.UserProfile;

/**
 *
 * @author its._royal_ankit
 */
public class DeliveryStaffLoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryStaffLOginFrame
     */
    
    private JFrame displayFrame;
    public DeliveryStaffLoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        myPanelDeliveryStaffLogin = new javax.swing.JPanel();
        lblDeliveryStaff = new javax.swing.JLabel();
        lblDeliveryStaffImage = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblEmailId = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblNewDeliveryStaffRegister = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        myPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(0, 153, 255));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        myPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 388, 173, 46));

        myPanelDeliveryStaffLogin.setBackground(new java.awt.Color(0, 153, 255));

        lblDeliveryStaff.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        lblDeliveryStaff.setForeground(new java.awt.Color(255, 255, 255));
        lblDeliveryStaff.setText("Delivery Staff");

        lblDeliveryStaffImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/icons/staff_login.png"))); // NOI18N

        lblLogin.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText(" Login");

        javax.swing.GroupLayout myPanelDeliveryStaffLoginLayout = new javax.swing.GroupLayout(myPanelDeliveryStaffLogin);
        myPanelDeliveryStaffLogin.setLayout(myPanelDeliveryStaffLoginLayout);
        myPanelDeliveryStaffLoginLayout.setHorizontalGroup(
            myPanelDeliveryStaffLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelDeliveryStaffLoginLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(myPanelDeliveryStaffLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeliveryStaffImage, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(myPanelDeliveryStaffLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelDeliveryStaffLoginLayout.createSequentialGroup()
                            .addComponent(lblDeliveryStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelDeliveryStaffLoginLayout.createSequentialGroup()
                            .addComponent(lblLogin)
                            .addGap(150, 150, 150)))))
        );
        myPanelDeliveryStaffLoginLayout.setVerticalGroup(
            myPanelDeliveryStaffLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelDeliveryStaffLoginLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblDeliveryStaff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogin)
                .addGap(18, 18, 18)
                .addComponent(lblDeliveryStaffImage, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        myPanel.add(myPanelDeliveryStaffLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        myPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 388, 172, 46));

        lblEmailId.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblEmailId.setForeground(new java.awt.Color(0, 153, 255));
        lblEmailId.setText("Enter Email");
        myPanel.add(lblEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 60, -1, -1));

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 153, 255));
        lblPassword.setText("Enter Password");
        myPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 191, -1, -1));

        txtEmailId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmailId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 1, true));
        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });
        myPanel.add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 107, 439, 40));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 243, 439, 40));

        lblNewDeliveryStaffRegister.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNewDeliveryStaffRegister.setForeground(new java.awt.Color(0, 153, 255));
        lblNewDeliveryStaffRegister.setText("New Staff Register Here");
        lblNewDeliveryStaffRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewDeliveryStaffRegisterMouseClicked(evt);
            }
        });
        myPanel.add(lblNewDeliveryStaffRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 302, 425, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator1.setAlignmentX(5.0F);
        jSeparator1.setAlignmentY(5.0F);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));
        myPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 331, 290, 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(myPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(myPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (!validateInputs()) {
            JOptionPane.showMessageDialog(null, "Company Name/Password cannot be left blank");
            return;
        }
        try {
            String emailId = txtEmailId.getText().trim();
            String password = String.valueOf(txtPassword.getPassword()).trim();
            password = PasswordEncryption.getEncryptedPassword(password);
            StaffPojo staff = StaffDAO.validate(emailId, password);
            if (staff == null) {
                JOptionPane.showMessageDialog(null, "Invalid UserId/Password. Try Again");
                clearAll();
                return;
            }
            UserProfile.setEmailId(staff.getEmailId());
            UserProfile.setUserName(staff.getStaffName());
            UserProfile.setUserId(staff.getStaffId());
            DeliveryStaffOptionFrame optionsFrame = new DeliveryStaffOptionFrame();
            optionsFrame.setVisible(true);
            this.dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "DB Error In SellerLoginFrame");
            ex.printStackTrace();
            return;
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    private boolean validateInputs() {

        if (txtEmailId.getText().trim().isEmpty() || String.valueOf(txtPassword.getPassword()).trim().isEmpty()) {
            return false;
        }
        return true;
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        displayFrame = new UserVerifyFrame();
        displayFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void lblNewDeliveryStaffRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewDeliveryStaffRegisterMouseClicked
        displayFrame = new AddDeliveryStaffFrame();
        displayFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblNewDeliveryStaffRegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryStaffLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryStaffLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryStaffLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryStaffLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliveryStaffLoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDeliveryStaff;
    private javax.swing.JLabel lblDeliveryStaffImage;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNewDeliveryStaffRegister;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPanel myPanel;
    private javax.swing.JPanel myPanelDeliveryStaffLogin;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    private void clearAll() {
        this.txtEmailId.setText("");
        this.txtPassword.setText("");
        this.txtEmailId.requestFocus();

    }
}
