/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yumxpress.gui;

import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import yumxpress.dao.CompanyDAO;
import yumxpress.pojo.CompanyPojo;
import yumxpress.utility.PasswordEncryption;
import yumxpress.utility.Validator;


/**
 *
 * @author its._royal_ankit
 */
public class SellerRegistrationFrame extends javax.swing.JFrame {

    /**
     * Creates new form SellerRegistrationFrame
     */
    
    private JFrame displayFrame;
    public SellerRegistrationFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        myPanelSellerRegister = new javax.swing.JPanel();
        lblSeller = new javax.swing.JLabel();
        lblSellerREgisterImage = new javax.swing.JLabel();
        lblRegistration = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblCompanyName = new javax.swing.JLabel();
        lblOwnerName = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtOwnerName = new javax.swing.JTextField();
        lblEmailId = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        lblSecurityKey = new javax.swing.JLabel();
        txtSecurityKey = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        myPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegister.setBackground(new java.awt.Color(153, 102, 255));
        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        myPanel.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 465, 144, -1));

        myPanelSellerRegister.setBackground(new java.awt.Color(153, 102, 255));

        lblSeller.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblSeller.setForeground(new java.awt.Color(255, 255, 255));
        lblSeller.setText("Seller");

        lblSellerREgisterImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/icons/seller register.jpg"))); // NOI18N

        lblRegistration.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblRegistration.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistration.setText("Registration");

        javax.swing.GroupLayout myPanelSellerRegisterLayout = new javax.swing.GroupLayout(myPanelSellerRegister);
        myPanelSellerRegister.setLayout(myPanelSellerRegisterLayout);
        myPanelSellerRegisterLayout.setHorizontalGroup(
            myPanelSellerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelSellerRegisterLayout.createSequentialGroup()
                .addGroup(myPanelSellerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanelSellerRegisterLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(myPanelSellerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(myPanelSellerRegisterLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(lblSeller))))
                    .addGroup(myPanelSellerRegisterLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblSellerREgisterImage)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        myPanelSellerRegisterLayout.setVerticalGroup(
            myPanelSellerRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelSellerRegisterLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblSeller, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(lblSellerREgisterImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        myPanel.add(myPanelSellerRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 615));

        btnBack.setBackground(new java.awt.Color(153, 102, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        myPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 465, 155, -1));

        lblCompanyName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCompanyName.setForeground(new java.awt.Color(153, 102, 255));
        lblCompanyName.setText("Company Name :");
        myPanel.add(lblCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 52, -1, 33));

        lblOwnerName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOwnerName.setForeground(new java.awt.Color(153, 102, 255));
        lblOwnerName.setText("Owner Name :");
        myPanel.add(lblOwnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 136, -1, 33));

        txtCompanyName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCompanyName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 255), 1, true));
        txtCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyNameActionPerformed(evt);
            }
        });
        myPanel.add(txtCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 53, 318, 33));

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(153, 102, 255));
        lblPassword.setText("Password :");
        myPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 211, -1, 33));

        txtOwnerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtOwnerName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 255), 1, true));
        txtOwnerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerNameActionPerformed(evt);
            }
        });
        myPanel.add(txtOwnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 137, 318, 33));

        lblEmailId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEmailId.setForeground(new java.awt.Color(153, 102, 255));
        lblEmailId.setText("Enter Email :");
        myPanel.add(lblEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 288, -1, 34));

        txtEmailId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmailId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 255), 1, true));
        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });
        myPanel.add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 290, 318, 33));

        lblSecurityKey.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSecurityKey.setForeground(new java.awt.Color(153, 102, 255));
        lblSecurityKey.setText("Enter Security Key :");
        myPanel.add(lblSecurityKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 364, -1, 33));

        txtSecurityKey.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSecurityKey.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 255), 1, true));
        txtSecurityKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSecurityKeyActionPerformed(evt);
            }
        });
        myPanel.add(txtSecurityKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 364, 318, 35));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 212, 318, 33));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(myPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        boolean result=validateInputs();
        if(!result){            
            return;
        }        
        try{
            CompanyPojo comp=new CompanyPojo();            
            comp.setCompanyName(txtCompanyName.getText().trim());
            comp.setOwnerName(txtOwnerName.getText().trim());            
            comp.setEmailId(txtEmailId.getText().trim());
            comp.setSecurityKey(txtSecurityKey.getText().trim());            
            char []pwd=txtPassword.getPassword();
            String pwdStr=String.valueOf(pwd);            
            pwdStr=PasswordEncryption.getEncryptedPassword(pwdStr);
            comp.setPassword(pwdStr);            
            result=CompanyDAO.addSeller(comp);
            if(result){
                JOptionPane.showMessageDialog(null,"Registration Successfull");                
                clearAll();
                return;                        }
            JOptionPane.showMessageDialog(null,"Registration UnSuccessfull");            
        }catch(SQLException sq){            
            JOptionPane.showMessageDialog(null,"DB ERROR IN SellerRegistrationFrame");
            sq.printStackTrace();        
        }
          
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        displayFrame = new SellerLoginFrame();
        displayFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyNameActionPerformed

    private void txtOwnerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerNameActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void txtSecurityKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSecurityKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSecurityKeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellerRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellerRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellerRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellerRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellerRegistrationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JLabel lblSecurityKey;
    private javax.swing.JLabel lblSeller;
    private javax.swing.JLabel lblSellerREgisterImage;
    private javax.swing.JPanel myPanel;
    private javax.swing.JPanel myPanelSellerRegister;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtOwnerName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSecurityKey;
    // End of variables declaration//GEN-END:variables


   private boolean validateInputs(){
       char pwd[]=this.txtPassword.getPassword();
       if(pwd.length==0||this.txtCompanyName.getText().trim().isEmpty()||this.txtOwnerName.getText().trim().isEmpty()||this.txtSecurityKey.getText().trim().isEmpty()||this.txtEmailId.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null,"Please fill all the details");
            return false;
       }
       
       if(Validator.isValidEmail(this.txtEmailId.getText().trim())==false){
            JOptionPane.showMessageDialog(null,"Please input a valid email id");
            return false;
       }
       return true;
   }
 
        private void clearAll() {        
            txtCompanyName.setText("");
            txtOwnerName.setText("");        
            txtEmailId.setText("");
            txtPassword.setText("");        
            txtSecurityKey.setText("");
            txtCompanyName.requestFocus();    }
}


