/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yumxpress.gui;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import yumxpress.dao.CompanyDAO;
import yumxpress.pojo.CompanyPojo;
import yumxpress.utility.OwnerProfile;
import yumxpress.utility.PasswordEncryption;

/**
 *
 * @author its._royal_ankit
 */
public class SellerLoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form SellerLoginFrame
     */
    public SellerLoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        myPanelSellerLogin = new javax.swing.JPanel();
        lblSellerLogin = new javax.swing.JLabel();
        lblSellerLoginImage = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblCompanyName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblNewSellerRegister = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        myPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(153, 102, 255));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        myPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 473, 178, 46));

        myPanelSellerLogin.setBackground(new java.awt.Color(153, 102, 255));

        lblSellerLogin.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        lblSellerLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblSellerLogin.setText("Seller Login");

        lblSellerLoginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/icons/seller.png"))); // NOI18N

        javax.swing.GroupLayout myPanelSellerLoginLayout = new javax.swing.GroupLayout(myPanelSellerLogin);
        myPanelSellerLogin.setLayout(myPanelSellerLoginLayout);
        myPanelSellerLoginLayout.setHorizontalGroup(
            myPanelSellerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelSellerLoginLayout.createSequentialGroup()
                .addGroup(myPanelSellerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanelSellerLoginLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblSellerLoginImage, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(myPanelSellerLoginLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblSellerLogin)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        myPanelSellerLoginLayout.setVerticalGroup(
            myPanelSellerLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelSellerLoginLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblSellerLogin)
                .addGap(36, 36, 36)
                .addComponent(lblSellerLoginImage, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        myPanel.add(myPanelSellerLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 639));

        btnBack.setBackground(new java.awt.Color(153, 102, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        myPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 473, 172, 46));

        lblCompanyName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCompanyName.setForeground(new java.awt.Color(153, 102, 255));
        lblCompanyName.setText("Enter Company Name");
        myPanel.add(lblCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 60, -1, -1));

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(153, 102, 255));
        lblPassword.setText("Enter Password");
        myPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 191, -1, -1));

        lblNewSellerRegister.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNewSellerRegister.setForeground(new java.awt.Color(153, 102, 255));
        lblNewSellerRegister.setText("<html><u>New Seller Register Here</u></html>");
        lblNewSellerRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewSellerRegisterMouseClicked(evt);
            }
        });
        myPanel.add(lblNewSellerRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 318, -1, -1));

        txtCompanyName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCompanyName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 102, 255), 1, true));
        txtCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyNameActionPerformed(evt);
            }
        });
        myPanel.add(txtCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 102, 427, 40));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 233, 427, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(myPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       if(!validateInputs()){
           JOptionPane.showMessageDialog(null, "Company Name/Password cannot be left blank");
           return;
       }
       try{
           String compName=txtCompanyName.getText().trim();
           String password=String.valueOf(txtPassword.getPassword()).trim();
           password=PasswordEncryption.getEncryptedPassword(password);
           CompanyPojo comp=CompanyDAO.validate(compName, password);
           if(comp==null){
               JOptionPane.showMessageDialog(null, "Invalid UserId/Password. Try Again");
               return;
           }
           OwnerProfile.setCompanyId(comp.getCompanyId());
           OwnerProfile.setCompanyName(comp.getCompanyName());
           OwnerProfile.setOwnerName(comp.getOwnerName());
           SellerOptionFrame optionFrame=new SellerOptionFrame();
           optionFrame.setVisible(true);
           this.dispose();
       }catch(SQLException sq){
           JOptionPane.showMessageDialog(null, "DB Error in SellerLogin");
           sq.printStackTrace();
           return;
       }
    }//GEN-LAST:event_btnLoginActionPerformed

    
    private boolean validateInputs(){
        if(txtCompanyName.getText().trim().isEmpty()||String.valueOf(txtPassword.getPassword()).trim().isEmpty()){
            return false;
        }
        return true;
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       UserVerifyFrame regFrame=new UserVerifyFrame();
       regFrame.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyNameActionPerformed

    private void lblNewSellerRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewSellerRegisterMouseClicked
        SellerRegistrationFrame regFrame=new SellerRegistrationFrame();
        regFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblNewSellerRegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellerLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellerLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellerLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellerLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellerLoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblNewSellerRegister;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSellerLogin;
    private javax.swing.JLabel lblSellerLoginImage;
    private javax.swing.JPanel myPanel;
    private javax.swing.JPanel myPanelSellerLogin;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
